{% set name = "freva-rest-server" %}
{% set version = "2601.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/freva-org/freva-nextgen/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1ffc6397ca175b7e945256467f86e15880653fb08bb21209a06f3b2f6d7738a2

build:
  number: 0
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - flit

  run:
    - python >={{ python_min }}
    - aiohttp
    - cloudpickle
    - email-validator
    - fastapi
    - fastapi-third-party-auth
    - httpx
    - h5netcdf
    - motor >=3.6
    - pyjwt
    - pymongo >=4.9
    - python-dotenv
    - python-dateutil
    - python-multipart
    - redis-py
    - requests
    - rich
    - rich-argparse
    - setuptools
    - tomli
    - typing_extensions
    - uvicorn
    - xarray
    - zarr

test:
  imports:
    - freva_rest
  commands:
    - freva-rest-server --help
    - python -m pip check
  requires:
    - python {{ python_min }}
    - pip
    - flit

about:
  summary: Server for the Free Evaluation and Analysis Framework (Freva)
  home: https://github.com/FREVA-CLINT/freva-nextgen
  description: |
    Freva (Free Evaluation System Framework) is a comprehensive platform
    designed to support researchers, especially in the atmospheric and climate
    science communities, in managing, searching, and analyzing large-scale
    datasets. It bridges the gap between data centers and user-defined tools,
    promoting efficient, reproducible, and collaborative research workflows.

    Intended Audience
    ------------------

    Freva is ideal for:

    - **Researchers and Scientists**: Streamline the search and evaluation of
      datasets hosted at various data centers.
    - **Data Analysts**: Integrate user-defined tools into a unified analysis
      framework.
    - **System Administrators**: Deploy scalable, reliable services to support
      data-heavy research.
    - **Research Institutions**: Enable reproducible data analysis workflows
      and foster collaboration among scientists.

    Whether you are analyzing climate model output, satellite observations, or
    observational data, Freva simplifies your workflow with its intuitive
    interface and robust backend services.

    Core Features
    -------------

    - **Data Discovery**: Quickly and intuitively search large datasets across
      distributed data centers.
    - **Tool Integration**: A unified interface to register, manage, and
      execute user-defined analysis tools.
    - **Reproducibility**: Apply tools in a consistent and reproducible manner,
      with a focus on scientific rigor.
    - **Extensibility**: Customize and expand the platform to meet the unique
      needs of your research team.

    Setup
    -----

    Setting up Freva involves deploying the necessary services and configuring
    them for your environment. Below is a high-level overview:

    Prerequisites
    ~~~~~~~~~~~~~

       - A Linux-based system with administrative privileges.
       - Conda installed to manage dependencies.
       - Access to required systemd services like Apache Solr and MongoDB.


    Running the Freva REST Server
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      1.  Start the REST server using:

        `freva-rest-server`

        This command launches the API endpoints that power Freva’s services,
        enabling you to interact with data and tools seamlessly.

    Why Choose Freva?
    -----------------

    Freva is designed for:

    - Seamless access to multi-terabyte datasets stored at data centers.
    - A scalable, modular architecture that adapts to diverse research needs.
    - An emphasis on fostering collaboration through reproducibility and
      interoperability.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://freva-clint.github.io/freva-nextgen
  dev_url: ttps://github.com/FREVA-CLINT/freva-nextgen
  doc_source_url: https://github.com/FREVA-CLINT/freva-nextgen/blob/main/freva-rest/README.md
  tags:
    - data-analysis
    - REST-API
    - climate-research
  keywords:
    - freva
    - REST-API
    - data framework


extra:
  recipe-maintainers:
    - antarcticrainforest
    - mo-dkrz
